### ISSUE TITLE
'_lock' is not defined on exit when using python 3

### ISSUE THREAD

**Issue by trygveaa** [mopidy/pyspotify#133]
When using pyspotify 2 (newest develop at current time) and python 3, I get this error when my script exits:

``` python
Exception ignored in: <function GcWeakrefs.__init__.<locals>.remove at 0x7f9c06ea4b70>
Traceback (most recent call last):
  File "/home/trygve/dev/pyspotify/venv3/lib/python3.4/site-packages/cffi-0.8.2-py3.4-linux-x86_64.egg/cffi/gc_weakref.py", line 12, in remove
  File "/home/trygve/dev/pyspotify/spotify/__init__.py", line 57, in wrapper
NameError: name '_lock' is not defined
```

It happens consistently, every time. The only code needed to make it happen is this:

``` python
import spotify
session = spotify.Session()
```

I'm running Python 3.4.0. When running Python 2.7.6, I don't get this error.

**Comment by jodal** [comment]
I started looking closer at this issue a while back. IIRC, I managed to reduce how often this happened, but not to get rid of it totally.

As a sign of how late in the interpreter shutdown this exception is raised, the following change does not hide the error as you would expect, but cause a `NameError: name 'NameError' is not defined` exception!

``` diff
diff --git a/spotify/__init__.py b/spotify/__init__.py
index 857bc84..1327d46 100644
--- a/spotify/__init__.py
+++ b/spotify/__init__.py
@@ -56,8 +56,11 @@ def serialized(f):

     @functools.wraps(f)
     def wrapper(*args, **kwargs):
-        with _lock:
-            return f(*args, **kwargs)
+        try:
+            with _lock:
+                return f(*args, **kwargs)
+        except NameError:
+            pass
     if not hasattr(wrapper, '__wrapped__'):
         # Workaround for Python < 3.2
         wrapper.__wrapped__ = f
```

**Comment by jodal** [comment]
This Python bug looks related: http://bugs.python.org/msg195244

**Comment by jodal** [comment]
This change effectively hides the error, but I really don't want to do this:

``` diff
diff --git a/spotify/__init__.py b/spotify/__init__.py
index 857bc84..1327d46 100644
--- a/spotify/__init__.py
+++ b/spotify/__init__.py
@@ -56,8 +56,11 @@ def serialized(f):

     @functools.wraps(f)
     def wrapper(*args, **kwargs):
-        with _lock:
-            return f(*args, **kwargs)
+        try:
+            with _lock:
+                return f(*args, **kwargs)
+        except:
+            pass
     if not hasattr(wrapper, '__wrapped__'):
         # Workaround for Python < 3.2
         wrapper.__wrapped__ = f
```

**Comment by jodal** [comment]
I can't reproduce this bug with cffi 1.0 development snapshot.

cffi 1.0 final will hopefully be released early next week. pyspotify will require cffi 1.0 as soon as it is available.
