### ISSUE TITLE
pyspotify 2.0.0b4 & libffi issue

### ISSUE THREAD

**Issue by hatarist** [mopidy/pyspotify#158]
I've ran into an issue with libffi while trying to install [pyportify](https://github.com/rckclmbr/pyportify) that requires pyspotify>=2.0.0b4.

```
Collecting pyspotify>=2.0.0b4 (from pyportify)
  Using cached pyspotify-2.0.0b4.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/r7/w9d0ryc55c319q_qpy2tmg2w0000gp/T/pip-build-h__Oyk/pyspotify/setup.py", line 76, in <module>
        'Topic :: Software Development :: Libraries',
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "<string>", line 15, in replacement_run
      File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/egg_info.py", line 206, in find_sources
      File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/egg_info.py", line 290, in run
      File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/egg_info.py", line 319, in add_defaults
      File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/sdist.py", line 118, in add_defaults
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "build/bdist.macosx-10.10-x86_64/egg/setuptools/command/build_py.py", line 28, in finalize_options
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_py.py", line 46, in finalize_options
        ('force', 'force'))
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/r7/w9d0ryc55c319q_qpy2tmg2w0000gp/T/pip-build-h__Oyk/pyspotify/setup.py", line 24, in finalize_options
        from spotify import ffi
      File "spotify/__init__.py", line 124, in <module>
        ffi, lib = _build_ffi()
      File "spotify/__init__.py", line 110, in _build_ffi
        ffi = cffi.FFI()
      File "/usr/local/lib/python2.7/site-packages/cffi/api.py", line 56, in __init__
        import _cffi_backend as backend
    ImportError: dlopen(/usr/local/lib/python2.7/site-packages/_cffi_backend.so, 2): Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
      Referenced from: /usr/local/lib/python2.7/site-packages/_cffi_backend.so
      Reason: image not found
```

I've installed python (2.7.9) via homebrew, perhaps it's the reason it tries to find a libffi in `/usr/local/opt/libffi/lib/libffi.6.dylib`instead of using the system one (`/usr/lib/libffi.dylib`)?

`brew list --versions` and `pip freeze` output: https://gist.github.com/hatarist/384f13aec8b42c067dbf
I'm using OS X 10.10.2.

Sorry again for that pull request!

**Comment by jodal** [comment]
Sorry, I'm not sure what's wrong here, so I haven't gotten around to answer or research this. Is it still an issue for you or did you figure it out?

**Comment by jodal** [comment]
No answer in 15 days. Closing.
