### ISSUE TITLE
Unknown playlist type PLACEHOLDER

### ISSUE THREAD

**Issue by rckclmbr** [mopidy/pyspotify#159]
In https://github.com/rckclmbr/pyportify/issues/25, someone has a playlist of type PLACEHOLDER, which is actually a documented playlist type, although I can't for the life of me figure out what it is.

You have it listed as a [playlist type](https://pyspotify.mopidy.com/en/latest/api/playlist/#spotify.PlaylistType), but aren't handling it when [loading](https://github.com/mopidy/pyspotify/blob/v2.x/develop/spotify/playlist_container.py#L178)

Any idea on how to resolve this?
```
2015-05-08 13:36:48,698 - pyportify.views - ERROR - Exception on /spotify/playlists [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/2.7/site-packages/pyportify/views.py", line 142, in spotify_playlists
    ret_playlists = fetch_spotify_playlists()
  File "/Library/Python/2.7/site-packages/pyportify/views.py", line 156, in fetch_spotify_playlists
    for playlist in playlists:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.py", line 581, in __iter__
    v = self[i]
  File "/Library/Python/2.7/site-packages/spotify/__init__.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/spotify/playlist_container.py", line 193, in __getitem__
    raise spotify.Error('Unknown playlist type: %r' % playlist_type)
Error: Unknown playlist type: <PlaylistType.PLACEHOLDER: 3>
127.0.0.1 - - [2015-05-08 13:36:48] "GET /spotify/playlists HTTP/1.1" 500 412 0.038552
```

**Comment by jodal** [comment]
According to the [libspotify docs](https://developer.spotify.com/docs/libspotify/12.1.51/group__session.html#gafdd7117213605e6f2671c4f289b44609):

> SP_PLAYLIST_TYPE_PLACEHOLDER 	Unknown entry.

So I guess all we can do is to ignore it instead of crashing.
