### ISSUE TITLE
OS X install issue: ld: library not found for -lbundle1.o

### ISSUE THREAD

**Issue by pilotkid** [mopidy/pyspotify#168]
## Hello I am getting this error when installing with MAC OSX
>InstallationError: Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/pyspotify

# The full install log is:

```
/usr/local/bin/pip run on Mon Jul  6 16:14:54 2015

Downloading/unpacking pyspotify

  Getting page https://pypi.python.org/simple/pyspotify/

  URLs to search for versions for pyspotify:

  * https://pypi.python.org/simple/pyspotify/

  Analyzing links from page https://pypi.python.org/simple/pyspotify/

    Skipping https://pypi.python.org/packages/cp27/p/pyspotify/pyspotify-2.0.0-cp27-none-macosx_10_6_intel.whl#md5=fabeb7104f3692e8705b1f9dd848aa08 (from https://pypi.python.org/simple/pyspotify/) because it is not compatible with this Python

    Skipping https://pypi.python.org/packages/cp27/p/pyspotify/pyspotify-2.0.0a1-cp27-none-macosx_10_6_intel.whl#md5=95f351debc8cb2a158e651cc80a6d1ca (from https://pypi.python.org/simple/pyspotify/) because it is not compatible with this Python

    Skipping https://pypi.python.org/packages/cp27/p/pyspotify/pyspotify-2.0.0b1-cp27-none-macosx_10_6_intel.whl#md5=eda6b5db5b30cc55f69f328cec136e63 (from https://pypi.python.org/simple/pyspotify/) because it is not compatible with this Python

    Skipping https://pypi.python.org/packages/cp27/p/pyspotify/pyspotify-2.0.0b2-cp27-none-macosx_10_6_intel.whl#md5=5697e4555fbc23aa61c7a0e04bde01c3 (from https://pypi.python.org/simple/pyspotify/) because it is not compatible with this Python

    Skipping https://pypi.python.org/packages/cp33/p/pyspotify/pyspotify-2.0.0a1-cp33-cp33m-macosx_10_6_intel.whl#md5=03d1d6cc6d7905e98381e91788f53495 (from https://pypi.python.org/simple/pyspotify/) because it is not compatible with this Python

    Skipping https://pypi.python.org/packages/cp33/p/pyspotify/pyspotify-2.0.0b1-cp33-cp33m-macosx_10_6_intel.whl#md5=45a49ab164088295d420c31b3e156b92 (from https://pypi.python.org/simple/pyspotify/) because it is not compatible with this Python

    Skipping https://pypi.python.org/packages/cp33/p/pyspotify/pyspotify-2.0.0b2-cp33-cp33m-macosx_10_6_intel.whl#md5=7dc4e995c2f31353a667dffdd904e80a (from https://pypi.python.org/simple/pyspotify/) because it is not compatible with this Python

    Skipping https://pypi.python.org/packages/cp34/p/pyspotify/pyspotify-2.0.0-cp34-cp34m-macosx_10_6_intel.whl#md5=27c9146abbce6af85bd810673400c8c2 (from https://pypi.python.org/simple/pyspotify/) because it is not compatible with this Python

    Skipping https://pypi.python.org/packages/cp34/p/pyspotify/pyspotify-2.0.0a1-cp34-cp34m-macosx_10_6_intel.whl#md5=f9ffdb9d2d05eea47a5fccd5d67558a5 (from https://pypi.python.org/simple/pyspotify/) because it is not compatible with this Python

    Skipping https://pypi.python.org/packages/cp34/p/pyspotify/pyspotify-2.0.0b1-cp34-cp34m-macosx_10_6_intel.whl#md5=d68993571efebba80db2af80798bc14f (from https://pypi.python.org/simple/pyspotify/) because it is not compatible with this Python

    Skipping https://pypi.python.org/packages/cp34/p/pyspotify/pyspotify-2.0.0b2-cp34-cp34m-macosx_10_6_intel.whl#md5=f0f5774ab59ea7938537bd762f809a41 (from https://pypi.python.org/simple/pyspotify/) because it is not compatible with this Python

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.1.tar.gz#md5=ea894bf2ed866618d8c11f067f0a00fb (from https://pypi.python.org/simple/pyspotify/), version: 1.1

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.10.tar.gz#md5=ff013983c360a263e6f50eeb19b4ac6f (from https://pypi.python.org/simple/pyspotify/), version: 1.10

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.11.tar.gz#md5=ffedc7261885f3416b2c37d51ed978c2 (from https://pypi.python.org/simple/pyspotify/), version: 1.11

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.12.tar.gz#md5=ce47484df6011ad9a3eeb37368f30880 (from https://pypi.python.org/simple/pyspotify/), version: 1.12

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.2.tar.gz#md5=17d5d27c7582785fb8e0fb9f963e0d3a (from https://pypi.python.org/simple/pyspotify/), version: 1.2

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.3.tar.gz#md5=1df2037ee31651a6113f1c646c6c83a1 (from https://pypi.python.org/simple/pyspotify/), version: 1.3

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.4.tar.gz#md5=40679703afab49667f03cc77fa39fbfb (from https://pypi.python.org/simple/pyspotify/), version: 1.4

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.5.tar.gz#md5=2e93ae359c3f16e64794c2b18a1b99bc (from https://pypi.python.org/simple/pyspotify/), version: 1.5

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.6.1.tar.gz#md5=88b3bb16a061d4c3868d5ffdee0d61fd (from https://pypi.python.org/simple/pyspotify/), version: 1.6.1

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.6.tar.gz#md5=1c4ff2791fdd6579d27b626c0331ff5a (from https://pypi.python.org/simple/pyspotify/), version: 1.6

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.7.1.tar.gz#md5=043dfbf7ad01e7235538fbd3ab127872 (from https://pypi.python.org/simple/pyspotify/), version: 1.7.1

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.7.tar.gz#md5=4f6aabc319172b4bd369c47ab164830e (from https://pypi.python.org/simple/pyspotify/), version: 1.7

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.8.1.tar.gz#md5=27af14cef03f9640f8f5a128f0e970fd (from https://pypi.python.org/simple/pyspotify/), version: 1.8.1

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.9.1.tar.gz#md5=11cb3b1ddccd792b625f6d813833e713 (from https://pypi.python.org/simple/pyspotify/), version: 1.9.1

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-1.9.tar.gz#md5=add0e40ae592a56b6650f6dbfd1cbb41 (from https://pypi.python.org/simple/pyspotify/), version: 1.9

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0.tar.gz#md5=bbe4b1dfadfc8eecb713f2ff5903f750 (from https://pypi.python.org/simple/pyspotify/), version: 2.0.0

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0a1.tar.gz#md5=636565439239600ce26f194e3d089fb4 (from https://pypi.python.org/simple/pyspotify/), version: 2.0.0a1

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0b1.tar.gz#md5=69786e466f19faa86e22a43d3f687226 (from https://pypi.python.org/simple/pyspotify/), version: 2.0.0b1

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0b2.tar.gz#md5=e4d47065b549b9f2811bc49be8ff96de (from https://pypi.python.org/simple/pyspotify/), version: 2.0.0b2

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0b3.tar.gz#md5=d48bae331095094fc61b2833c1963f95 (from https://pypi.python.org/simple/pyspotify/), version: 2.0.0b3

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0b4.tar.gz#md5=0ee5ed3e1101e025774cf0558a496e96 (from https://pypi.python.org/simple/pyspotify/), version: 2.0.0b4

    Found link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0b5.tar.gz#md5=54727c834fd90cd3d9a0e3e8efab1136 (from https://pypi.python.org/simple/pyspotify/), version: 2.0.0b5

    Skipping http://github.com/mopidy/pyspotify/tarball/develop#egg=pyspotify-dev (from https://pypi.python.org/simple/pyspotify/) because it is externally hosted.

  Ignoring link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0a1.tar.gz#md5=636565439239600ce26f194e3d089fb4 (from https://pypi.python.org/simple/pyspotify/), version 2.0.0a1 is a pre-release (use --pre to allow).

  Ignoring link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0b1.tar.gz#md5=69786e466f19faa86e22a43d3f687226 (from https://pypi.python.org/simple/pyspotify/), version 2.0.0b1 is a pre-release (use --pre to allow).

  Ignoring link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0b2.tar.gz#md5=e4d47065b549b9f2811bc49be8ff96de (from https://pypi.python.org/simple/pyspotify/), version 2.0.0b2 is a pre-release (use --pre to allow).

  Ignoring link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0b3.tar.gz#md5=d48bae331095094fc61b2833c1963f95 (from https://pypi.python.org/simple/pyspotify/), version 2.0.0b3 is a pre-release (use --pre to allow).

  Ignoring link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0b4.tar.gz#md5=0ee5ed3e1101e025774cf0558a496e96 (from https://pypi.python.org/simple/pyspotify/), version 2.0.0b4 is a pre-release (use --pre to allow).

  Ignoring link https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0b5.tar.gz#md5=54727c834fd90cd3d9a0e3e8efab1136 (from https://pypi.python.org/simple/pyspotify/), version 2.0.0b5 is a pre-release (use --pre to allow).

  Using version 2.0.0 (newest of versions: 2.0.0, 1.12, 1.11, 1.10, 1.9.1, 1.9, 1.8.1, 1.7.1, 1.7, 1.6.1, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1)

  Downloading from URL https://pypi.python.org/packages/source/p/pyspotify/pyspotify-2.0.0.tar.gz#md5=bbe4b1dfadfc8eecb713f2ff5903f750 (from https://pypi.python.org/simple/pyspotify/)

  Running setup.py (path:/private/tmp/pip_build_root/pyspotify/setup.py) egg_info for package pyspotify

    _configtest.c:1:1: error: thread-local storage is not supported for the current target

    __thread int some_threadlocal_variable_42;

    ^

    1 error generated.

    Note: will not use '__thread' in the C code

    The above error message can be safely ignored

    ld: library not found for -lbundle1.o

    clang: error: linker command failed with exit code 1 (use -v to see invocation)

    Traceback (most recent call last):

      File "<string>", line 17, in <module>

      File "/private/tmp/pip_build_root/pyspotify/setup.py", line 47, in <module>

        'Topic :: Software Development :: Libraries',

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup

        _setup_distribution = dist = klass(attrs)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 261, in __init__

        self.fetch_build_eggs(attrs.pop('setup_requires'))

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 286, in fetch_build_eggs

        replace_conflicting=True,

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 632, in resolve

        dist = best[req.key] = env.best_match(req, ws, installer)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 872, in best_match

        return self.obtain(req, installer)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 884, in obtain

        return installer(requirement)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 337, in fetch_build_egg

        return cmd.easy_install(req)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 613, in easy_install

        return self.install_item(spec, dist.location, tmpdir, deps)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 643, in install_item

        dists = self.install_eggs(spec, download, tmpdir)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 833, in install_eggs

        return self.build_and_install(setup_script, setup_base)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1055, in build_and_install

        self.run_setup(setup_script, setup_base, args)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1043, in run_setup

        raise DistutilsError("Setup script exited with %s" % (v.args[0],))

    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1

    Complete output from command python setup.py egg_info:

    _configtest.c:1:1: error: thread-local storage is not supported for the current target



__thread int some_threadlocal_variable_42;



^



1 error generated.



Note: will not use '__thread' in the C code



The above error message can be safely ignored



ld: library not found for -lbundle1.o



clang: error: linker command failed with exit code 1 (use -v to see invocation)



Traceback (most recent call last):



  File "<string>", line 17, in <module>



  File "/private/tmp/pip_build_root/pyspotify/setup.py", line 47, in <module>



    'Topic :: Software Development :: Libraries',



  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup



    _setup_distribution = dist = klass(attrs)



  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 261, in __init__



    self.fetch_build_eggs(attrs.pop('setup_requires'))



  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 286, in fetch_build_eggs



    replace_conflicting=True,



  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 632, in resolve



    dist = best[req.key] = env.best_match(req, ws, installer)



  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 872, in best_match



    return self.obtain(req, installer)



  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 884, in obtain



    return installer(requirement)



  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py", line 337, in fetch_build_egg



    return cmd.easy_install(req)



  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 613, in easy_install



    return self.install_item(spec, dist.location, tmpdir, deps)



  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 643, in install_item



    dists = self.install_eggs(spec, download, tmpdir)



  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 833, in install_eggs



    return self.build_and_install(setup_script, setup_base)



  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1055, in build_and_install



    self.run_setup(setup_script, setup_base, args)



  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1043, in run_setup



    raise DistutilsError("Setup script exited with %s" % (v.args[0],))



distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1



----------------------------------------

Cleaning up...

  Removing temporary dir /private/tmp/pip_build_root...

Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/pyspotify

Exception information:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main

    status = self.run(options, args)

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run

    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req.py", line 1229, in prepare_files

    req_to_install.run_egg_info()

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info

    command_desc='python setup.py egg_info')

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess

    % (command_desc, proc.returncode, cwd))

InstallationError: Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/pyspotify

```

_______________
Any help is GREATLY appreciated!

**Comment by jodal** [comment]
I think the important part of the error message is:

```
ld: library not found for -lbundle1.o
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Googling this error, it seems that "reinstalling" Xcode is the solution. To do that, run:

```
xcode-select --install
```
