### ISSUE TITLE
AssertionError: Invalid application key; expected 321 bytes, got 803 bytes

### ISSUE THREAD

**Issue by tomchambers2** [mopidy/pyspotify#171]
I'm running the version built from source on Raspbian Wheezy with Python 2.7.3. I've setup a super simple script but it's rejecting my spotify API key which I downloaded today from https://devaccount.spotify.com/my-account/keys/.

First line of the key looks like this: ```0140 9dc8 3486 1984 0ac3 28e8 6936 21e3```

```
$ cat index.py 
import spotify
session = spotify.Session()
```

```
$ python index.py 
Traceback (most recent call last):
  File "index.py", line 2, in <module>
    session = spotify.Session()
  File "/root/spottest/env/local/lib/python2.7/site-packages/pyspotify-2.0.2-py2.7-linux-armv6l.egg/spotify/__init__.py", line 58, in wrapper
    return f(*args, **kwargs)
  File "/root/spottest/env/local/lib/python2.7/site-packages/pyspotify-2.0.2-py2.7-linux-armv6l.egg/spotify/session.py", line 55, in __init__
    self.config.load_application_key_file()
  File "/root/spottest/env/local/lib/python2.7/site-packages/pyspotify-2.0.2-py2.7-linux-armv6l.egg/spotify/config.py", line 128, in load_application_key_file
    self.application_key = fh.read()
  File "/root/spottest/env/local/lib/python2.7/site-packages/pyspotify-2.0.2-py2.7-linux-armv6l.egg/spotify/config.py", line 110, in application_key
    'Invalid application key; expected 321 bytes, got %d bytes' % size)
AssertionError: Invalid application key; expected 321 bytes, got 803 bytes
```

**Comment by jodal** [comment]
It looks like your file contains bytes encoded in hexadecimal. Is that
right? It should be raw bytes, without any textual representation. The
increased file size indicates the same.

**Comment by tomchambers2** [comment]
Yes that's it. Not sure how it got converted, possibly through opening in sublime text. I copied it across without opening and it works now. Thanks.
