### ISSUE TITLE
ALSAAudioError: File descriptor in bad state

### ISSUE THREAD

**Issue by johannilsson** [mopidy/pyspotify#88]
Hi, I getting the following on a RaspberryPI with version 1.10 using the `jukebox.py` sample app when it switching track. The `next` command works but not when it automatically switches.

    jukebox> play 0
    Loading playlist theshopbox
    Loading Sad-Eyed Lady Of The Lowlands from theshopbox
    Playing
    jukebox> next
    Stopping
    Loading Bleecker Street from theshopbox
    Playing
    jukebox> next
    Stopping
    Loading Son Of A Preacher Man from theshopbox
    Playing
    jukebox> Traceback (most recent call last):
      File "jukebox.py", line 461, in <module>
        session_m.connect()
      File "/usr/local/lib/python2.7/dist-packages/spotify/manager/session.py", line 81, in connect
        self.loop(self.session) # returns on logged out
      File "/usr/local/lib/python2.7/dist-packages/spotify/manager/session.py", line 97, in loop
        session, *message['args'])
      File "jukebox.py", line 397, in music_delivery_safe
        return self.audio.music_delivery(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/spotify/audiosink/alsa.py", line 23, in music_delivery
        self._call_if_needed(self._device.setperiodsize, num_frames)
      File "/usr/local/lib/python2.7/dist-packages/spotify/audiosink/__init__.py", line 127, in _call_if_needed
        func(*args, **kwargs)
    alsaaudio.ALSAAudioError: File descriptor in bad state

**Comment by jodal** [comment]
Due to the imminent release of the 2.0 rewrite of pyspotify, this will probably never be done. Closing.
